### ISSUE TITLE
SSL/TLS Python <--> Rust issues

### ISSUE THREAD

**Issue by Wiezzel** [golemfactory/capnp-playground#2]
### Summary
Python SSL-enabled client won't work with Rust SSL-enabled server. And vice versa.

---

### Details
This is the interoperability matrix for implemented clients and servers:

| Servers :point_right: <br> Clients :point_down:  | [Python <br> (plain)](https://github.com/golemfactory/capnp-playground/blob/master/python/server.py) | [Rust <br> (plain)](https://github.com/golemfactory/capnp-playground/blob/master/rust/helloworld/src/bin/server.rs) | [Python <br> (SSL)](https://github.com/golemfactory/capnp-playground/blob/master/python/ssl_server.py) | [Rust <br> (native SSL)](https://github.com/golemfactory/capnp-playground/blob/master/rust/helloworld/src/bin/native_ssl_server.rs) | [Rust <br> (OpenSSL)](https://github.com/golemfactory/capnp-playground/blob/master/rust/helloworld/src/bin/openssl_server.rs) |
|-|-|-|-|-|-|
| [Python <br> (plain)](https://github.com/golemfactory/capnp-playground/blob/master/python/client.py) | ✔️  | ✔️ | | | |
| [Rust <br> (plain)](https://github.com/golemfactory/capnp-playground/blob/master/rust/helloworld/src/bin/client.rs) | ✔️  | ✔️  | | | |
| [Python <br> (SSL)](https://github.com/golemfactory/capnp-playground/blob/master/python/ssl_client.py) | | | ✔️  | ❌ Case 1 | ❌ Case 2 |
| [Rust <br> (native SSL)](https://github.com/golemfactory/capnp-playground/blob/master/rust/helloworld/src/bin/native_ssl_client.rs) | | | ❌ Case 3 | ✔️  | ✔️ |

---

#### Client error:
```
Sending request...
Traceback (most recent call last):
  File "python/ssl_client.py", line 32, in <module>
    main(*sys.argv[1:])
  File "python/ssl_client.py", line 27, in main
    result = helloworld.sayHello(request=request).wait()
  File "capnp\lib\capnp.pyx", line 1932, in capnp.lib.capnp._RemotePromise.wait
capnp.lib.capnp.KjException: capnp\serialize-async.c++:90: disconnected: expected segmentCount() < 512; Message has too many segments.
stack: 0 0 7ffe0da63af8 7ffe0dafe50d 7ffe0dafde8f 5ccc2f57 5ccc2502 5cc98b38 5ccc336a 5ccbc258 5cc9b384 5ccc336a 5cc9f852 5cc9f7b0 5cc9f75a 5ce1a818 5ce1afb8 5ce1a6f6 5cd6af43 5ccee579 1c7b126c 7ffe57ae81f3 7ffe57f6a250
```
#### Server error:
```
Error { kind: Failed, description: "Token dostarczony do funkcji jest nieprawidłowy. (os error -2146893048)" }
```
Message translation: "The token supplied to the function is invalid" (known as `SEC_E_INVALID_TOKEN` code: 0x80090308)

---

#### Client error:
```
Sending request...
Traceback (most recent call last):
  File "python/ssl_client.py", line 32, in <module>
    main(*sys.argv[1:])
  File "python/ssl_client.py", line 27, in main
    result = helloworld.sayHello(request=request).wait()
  File "capnp\lib\capnp.pyx", line 1932, in capnp.lib.capnp._RemotePromise.wait
capnp.lib.capnp.KjException: capnp\serialize-async.c++:90: disconnected: expected segmentCount() < 512; Message has too many segments.
stack: 0 0 7ffe0da63af8 7ffe0dafe50d 7ffe0dafde8f 5ccc2f57 5ccc2502 5cc98b38 5ccc336a 5ccbc258 5cc9b384 5ccc336a 5cc9f852 5cc9f7b0 5cc9f75a 5ce1a818 5ce1afb8 5ce1a6f6 5cd6af43 5ccee579 1c7b126c 7ffe57ae81f3 7ffe57f6a250
```
#### Server error:
```
Error { kind: Failed, description: "unexpected EOF" }
```

---

#### Client error:
```
Sending request...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Failed, description: "Token dostarczony do funkcji jest nieprawidłowy. (os error -2146893048)" }', src\libcore\result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
Message translation: "The token supplied to the function is invalid" (known as SEC_E_INVALID_TOKEN code: 0x80090308)
#### Server error:
None. No error raised at all.

---

### Other remarks

[Related issue](https://github.com/capnproto/pycapnp/issues/105)

**Comment by Wiezzel** [comment]
### The cause has been identified:
Cap'n Proto server just takes `fileno()` from the supplied socket so the SSL layer is completely ignored:

https://github.com/capnproto/pycapnp/blob/29e63de41d9f0598437487863edf6ccb1f5e840a/capnp/lib/capnp.pyx#L2266
https://github.com/capnproto/pycapnp/blob/29e63de41d9f0598437487863edf6ccb1f5e840a/capnp/lib/capnp.pyx#L2371

**Comment by Wiezzel** [comment]
KJ has [OpenSSL bindings](https://github.com/capnproto/capnproto/blob/06a7136708955d91f8ddc1fa3d54e620eacba13e/c%2B%2B/src/kj/compat/tls.h). I tried to use them to implement TLS-enabled Python server but I failed to make it work. [Here](https://github.com/Wiezzel/pycapnp/commit/f1d3fcbbd99e5e862fff734e8ca4668b1bf09d34) is the attempt. It requires a [custom build](https://github.com/Wiezzel/capnproto/commit/9ab908e471fb304bc66b05ad24587dc1533c22d3) of libcapnp to compile.
